### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by szaghi** [aamaricci/SciFortran#1]
Hi Adriano,

I follow your progress with interest, I think this project has great potential. However, the lack of documentation limits me (and maybe others) to digg deeper. I am counscious that writing documentation is a time-consuming effort, but it has not less relevance of the code itself (IMHO). Have you a plan to add documentation in the near future (or it is already here and I am so blind to have missed it)?

Thank you very much for sharing your work.

Stefano

**Comment by aamaricci** [comment]
Hi Stefano, 
thanks for your interest.

You're right about the missing documentation. 
This is a feature I'd like to add. I mean it is in the *todo* list, together with other extensions I have in my pipeline (sparse matrices, sparse linalg, ode solvers, a better interface to quadpack, etc.). 

In any case my plan for the future would be to use FORD. I played a bit with other tools, but this one looks pretty nice and well suited for SciFor. 

This, and the aforementioned extensions, could be an excellent basis for a collaborative work, but on the other hand I understand that with no documentation whatsoever that's kind of desperate act (and the main reason why I did not deployed the library to FOSS). 

Cheers,
A

**Comment by szaghi** [comment]
@aamaricci Great! Happy to read this! FORD is really a cool tool.

I will continue to track this project. 

See you soon.

**Comment by funnell** [comment]
Just to chime in, I'm also interested in this project. But, without documentation it's difficult to get started...

**Comment by aamaricci** [comment]
Hi. Thanks for your interest. 
I should definitively start working on that. 
A

**Comment by band-a-prend** [comment]
I'm also interested in documentation as the first looked example for python scipy as reference for this project used lambda function passed into.

E.g. it was general integration (quad): https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html
